Repository HYF-Class21/agile-development-group1-loruki-rebuild, pull requests merged in 2023-04, with the labels that each got.

#3 update project definition
  README.md
Labels: md

#5 add communication file
  planning/communication.md
Labels: md

#12 add project's assigments to communication file
  planning/communication.md
Labels: md

#11 adding group constraints
  planning/constraints.md
Labels: md

#16 README.md add information about technologies
  README.md
Labels: md

#17 adding all three wireframes images and editing design.md
  planning/design.md
  planning/docs-wireframe.png
  planning/features-wireframe.png
  planning/homepage-wireframe.png
Labels: documentation, md, planning

#20 Backlog
  planning/backlog.md
Labels: md

#18 update user-personas.md
  planning/user-personas.md
Labels: md

#22 adding development strategy with nav bar section modification only
  planning/development-strategy.md
Labels: md

#21 updating README.md
  README.md
  planning/screenshot-docs.png
  planning/screenshot-features.png
  planning/screenshot-homepage.png
Labels: md

#27 adding retrospective file
  planning/retrospective.md
Labels: md

#28 update the Docs file
  pages/docs.html
  styles/index.css
Labels: html, css

#26 adding homepage steps to development-strategy.md
  planning/development-strategy.md
Labels: md

#46 Homepage languages
  homepage.html
  planning/development-strategy.md
Labels: html

#29 formating fixes
  planning/development-strategy.md
Labels: md

#43 update docs.html
  pages/docs.html
Labels: html
